on:
  push:
    branches:
      - 'main'

name: Stable

jobs:
  test:
    name: Test project
    runs-on: macos-11 # add other OS later
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: cargo-bundle
  build:
    name: Build project
    permissions: write-all
    runs-on: macos-latest # add other OS later
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bundle
      - uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: GoKey.app
          path: target/release/bundle/osx/GoKey.app
          retention-days: 2
      - name: Release nightly
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd target/release/bundle/osx
          zip -r GoKey.zip GoKey.app
          gh release delete-asset nightly-build GoKey.zip
          gh release upload nightly-build GoKey.zip
